### ISSUE TITLE
compile error on node v0.12.0

### ISSUE THREAD

**Issue by hdwong** [Sannis/node-mysql-libmysqlclient#188]
I am using Mac OS X, and this module had compiled successfully on node v0.10.x, when I upgrade node to v0.12.0 and recompile this module, it throw the following error:

> child_process: customFds option is deprecated, use stdio instead.
  CXX(target) Release/obj.target/mysql_bindings/src/mysql_bindings.o
In file included from ../src/mysql_bindings.cc:17:
In file included from ../src/./mysql_bindings_connection.h:22:
In file included from ../src/./mysql_bindings.h:14:
../node_modules/nan/nan.h:339:13: error: no member named 'New' in 'v8::String'
    return  _NAN_ERROR(v8::Exception::Error, errmsg);
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:319:50: note: expanded from macro '_NAN_ERROR'
\# define _NAN_ERROR(fun, errmsg) fun(v8::String::New(errmsg))
                                     \~\~\~\~\~\~\~\~\~\~\~\~^
../node_modules/nan/nan.h:343:5: error: no member named 'ThrowException' in namespace 'v8'
    _NAN_THROW_ERROR(v8::Exception::Error, errmsg);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by ebramanti-techempower** [comment]
Same issue, unable to build on node v0.12, anyone know of a fix?

**Comment by wangbinlml** [comment]
me too, compile error on node v0.12.0

**Comment by alexeygritsenko** [comment]
v0.12.2 не работает также. исправьте плиз

**Comment by Sannis** [comment]
Will be fixed in #192.
